language: 'python'
dist: xenial
python:
  - '3.7'
node_js:
  - '10.16.0'
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cat ci/database_override.py >> plinyproj/settings.py
  - cd next-app && npm ci
  - cd ..
  - mysql -e 'CREATE DATABASE pliny CHARSET utf8mb4;'
script:
  - pytest --cov
  - cd next-app && npm test
sevices:
  - mysql
after_success:
  - cd .. && codecov
