language: 'python'

python:
  - '3.6'
  - '3.5'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cat ci/database_override.py >> plinyproj/settings.py

script:
  - python -m pytest

sevices:
  - mysql
