language: 'python'

python:
  - '3.6'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cat ci/database_override.py >> plinyproj/settings.py

script:
  - pytest --cov

sevices:
  - mysql

after_success:
  - codecov
