language: 'python'

python:
  - '3.6'
node_js:
  - "8.9.4"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cat ci/database_override.py >> plinyproj/settings.py
  - cd test_js && npm install && cd ..
script:
  - pytest --cov

sevices:
  - mysql

after_success:
  - codecov
