language: 'python'
python:
  - '3.6'
node_js:
  - '10.16.0'
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install codecov
  - cat ci/database_override.py >> plinyproj/settings.py
  - cd next-app && npm install
  - cd ..
script:
  - pytest --cov
  - cd next-app && npm test
sevices:
  - mysql
after_success:
  - codecov
  - cd .. && codecov
