version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foo
    ports:
      - 3306:3306
    volumes:
      - ./:/dumps
      - mysql-vol:/var/lib/mysql
  psql-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - psql-vol:/var/lib/postgresql/data
      - ./:/dumps
    security_opt:
      - seccomp=unconfined
volumes:
  mysql-vol:
  psql-vol:
