version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - env
    volumes:
      - psql-vol:/var/lib/postgresql/data
  django-app:
    build:
      context: ./backend
      target: dev
    env_file:
      - env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/opt/app
  next-app:
    build:
      context: ./frontend
      target: dev
    env_file:
      - env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/opt/app
volumes:
  psql-vol:
