name: Build and Push Images

on:
  push:
    tags:
      - "*"
    branch:
      - "master"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push backend
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.digitalocean.com/gricks
          path: backend
          repository: pliny-backend
          tag_with_ref: true
      - name: Build and push frontend
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.digitalocean.com/gricks
          path: frontend
          repository: pliny-frontend
          tag_with_ref: true
